// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogPostFields {
    /** Slug */
    slug: string;

    /** Title */
    title: string;

    /** Summary */
    summary: string;

    /** Hero Image */
    heroImage: Asset;

    /** Date */
    date: string;

    /** Author */
    author: string;

    /** Category */
    categoryName: string;

    /** Carousel */
    carousel?: Record<string, any> | undefined;

    /** Details */
    details: Document;

    /** Related Blogs */
    relatedBlogs?: IBlogPost[] | undefined;
}

export interface IBlogPost extends Entry<IBlogPostFields> {
    sys: {
        id: string;
        type: string;
        createdAt: string;
        updatedAt: string;
        locale: string;
        contentType: {
            sys: {
                id: "blogPost";
                linkType: "ContentType";
                type: "Link";
            };
        };
    };
}

export type CONTENT_TYPE = "blogPost";

export type IEntry = IBlogPost;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
