import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import Draft from "../components/Draft";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex min-h-screen flex-col items-center justify-between p-12">
                    <section className="w-full mx-auto container space-y-12 px-4 md:px-6 flex flex-col items-center justify-center space-y-8 max-w-[1200px] content-center">
                        <div
                            id="control-panel"
                            className="border border-blue-500 rounded w-full p-4 flex gap-4 bg-slate-100"
                        >
                            <p className="font-bold">Control Panel</p>
                            <Draft />
                        </div>
                        <Nav />
                        {children}
                        <Footer />
                    </section>
                </main>
            </body>
        </html>
    );
}
